# render.yaml
services:
  - type: worker
    name: deobfuscator-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: DISCORD_TOKEN
        sync: false # Set this to 'true' if you want to sync changes from Render dashboard to git
